### ISSUE TITLE
[namespace]

### ISSUE THREAD

**Issue by ashok-an** [ashok-an/rbac-helm#1]
```yaml
inputs:
  teamName: scorpio
  emailPrefix: scorpio #@cisco.com
  webexRoomName: scorpio-alerts
  webexRoomId: abcd1234
  oidcGroup: scorpio-oidc

namespace:
  name: scorpio-ns

serviceAccount:
  name: scorpio-sa

ingress:
  ip: 127.0.0.1

limits:
  maxCpu: "5"
  maxMemory: 20Gi
  minCpu: ".1"
  minMemory: 128Mi
  maxGpu: 0
  maxStorage: 50Gi
  maxEphemeralStorage: 30Gi
  counts:
    pods: 30
    services: 10
    loadbalancers: 0
    nodeports: 1
    secrets: 10
    configmaps: 10
    persistentvolumeclaims: 10
    deployments.apps: 10
    statefulsets.apps: 5
    jobs.batch: 10
    cronjobs.batch: 10
```
